name: CI for Codecov

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # possible to replace to macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Install Playwright
        run: |
          pip install playwright
          npx playwright install --with-deps
        
      - name: Run tests with coverage
        run: pytest -s --cov=tests --cov-report=xml 

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }} 
