name: Python Lint

on:
    push:
      branches: [add-codecov]
    pull_request:
      branches: [add-codecov]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pylint 

      - name: Run pylint (deep analysis)
        run: pylint --disable=C0114,C0115,C0116 $(git ls-files '*.py')
